app:
  jyp:
    url: http://localhost:8080

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jyp
    username: jypdev
    password: password
    platform: postgres
    hikari:
      auto-commit: false
      idle-timeout: 10000
      minimumIdle: 10
      maximum-pool-size: 30
      read-only: false
      connection-timeout: 20000
      data-source-properties:
        stringtype: unspecified
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true